# Site data
name: Johnie Hjelm
title: Human interface designer & front end developer
wired: Wired In AB
baseurl: ""
journal: http://johniehjelm.me

# Social
twitter: johniehjelm
facebook: johniehjelm
github: johnie

# Build settings
markdown: kramdown
permalinks: /:title
timezone: Europe/Stockholm

# Includes / Exclude
include: ['.htaccess']
exclude: ['README.md', 'node_modules/', 'Gruntfile.js', 'package.json', 'config.rb']

# Collections
collections:
  work:
    output: true
