# Site data
name: Johnie Hjelm
title: Human interface designer & front end developer
wired: Wired In AB
baseurl: ""
journal: http://johniehjelm.me
email: johnie@hjelm.im

# Build settings
markdown: kramdown
permalinks: /:title
timezone: Europe/Stockholm

# Includes / Exclude
include: ['.htaccess']
exclude: ['README.md', 'node_modules/', 'Gulpfile.js', 'package.json', 'config.rb', 'assets/js', 'assets/scss', 'assets/images']

# Collections
collections:
  work:
    output: true
